# This file can be saved and live changes reflected (no sourcing)
# This theme affects your terminal (tmux does not)
import = [ "~/.config/alacritty/tokyo-night.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 800
padding.y = 20

decorations = "Buttonless"

opacity = 0.50
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 16 

