[env]
TERM = "xterm-256color"

[window]
padding.x = 40
padding.y = 40

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 15 
