require("sfrend.plugins-setup")
require("sfrend.core.options")
require("sfrend.core.keymaps")
require("sfrend.core.colorscheme")
require("sfrend.plugins.comment")
require("sfrend.plugins.nvim-tree")
require("sfrend.plugins.lualine")
require("sfrend.plugins.telescope")
